name: "Build"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: "Build with web-ext"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: src
          verbose: true
          channel: listed

      - name: "Upload Artifact"
        uses: actions/upload-artifact@master
        with:
          name: target.xpi
          path: ${{ steps.web-ext-build.outputs.target }}